name: bld

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  blds:
    strategy:
      matrix:
        registry: ["ghcr.io/ngam"]
        subject: ["cgc"]
        container: ["tf"]
    runs-on: ubuntu-latest
    container:
      image: quay.io/singularity/singularity:v3.8.3
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Singularity
        run: |
          sudo -E singularity build container.sif ${{ matrix.subject }}/${{ matrix.container }}/Singularity
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ngam --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/sifs:${{ matrix.subject }}_${{ matrix.container }}
